version: '3.7'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306  
    environment:
      MYSQL_USER: blackzone
      MYSQL_PASSWORD: 492AQZBcykLVKpsXvsGysMSgvSgPkJ
      MYSQL_ROOT_PASSWORD: 492AQZBcykLVKpsXvsGysMSgvSgPkJ
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default  
  
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8092:80  
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 512M
      MYSQL_ROOT_PASSWORD: 492AQZBcykLVKpsXvsGysMSgvSgPkJ
      MYSQL_PASSWORD: 492AQZBcykLVKpsXvsGysMSgvSgPkJ
      VIRTUAL_HOST: db.blackzone.mx
      LETSENCRYPT_HOST: db.blackzone.mx
    networks:
      - default  

networks:
  default:
    external:
      name: npm

volumes:
  mysql_data:


